[package]
name = "smart_home"
version = "0.1.1"
edition = "2024"
authors = ["Dmitry Lozovoy"]
description = "Otus Rust Developer Homework: Smart home library"
readme = "../readme.md"
repository = "https://github.com/free0ON/otus_rust_hw"

[[example]]
name = "home"
crate-type = ["bin"]

[dependencies]
rand = "0.9"
